### ISSUE TITLE
Why is restic_backup.sh managing its own logfile?

### ISSUE THREAD

**Issue by msteinhoff** [erikw/restic-systemd-automatic-backup#3]
Hi,

```bash
# Redirect stdout ( > ) into a named pipe ( >() ) running "tee" to a file, so we can observe the status by simply tailing the log file.
me=$(basename "$0")
now=$(date +%F_%R)
log_dir=/var/local/log/restic
log_file="${log_dir}/${now}_${me}.$$.log"
test -d $log_dir || mkdir -p $log_dir
exec > >(tee -i $log_file)
exec 2>&1
```

Is there any non-obvious reason for doing this instead of printing to stdout and using `journalctl -f -u restic-backup.service`?

**Comment by erikw** [comment]
@msteinhoff You are right, much easier. I added it to README.

Those  lines are my boilerplate lines I have in many of my automated tasks. Some of my scripts I share between environments. `restic_backup.sh` I also use on FreeBSD systems for example, so implementing some rudimentary cross-platform solutions makes it easier for me to deploy the same solutions to my systems. But since this is a systemd specific example in this repo, lets use journalctl :)

**Comment by msteinhoff** [comment]
Awesome, thanks. :)

I'd also suggest adding `--verbose` to `restic_backup.sh` and `restic_check.sh`, otherwise journalctl is not of much use because restic won't print any status updates until its finished. At least on my machine with restic 0.92. :)

**Comment by erikw** [comment]
I like the idea!

https://github.com/erikw/restic-systemd-automatic-backup/commit/960cc9d42feec494e7141cb37f7e1c5031127200
